package pojos;

import com.google.gson.annotations.Expose;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor

public class UsersPOJO {

    // 1. Declaring instance variables, which will be then instantiated upon User Object creation with the help of Constructor and this. keyword.
    //    These variables, when instantiated will define the State of a User Object, and will become it's private parameters.
    //    Some of them, such as "id" will be auto-generated by the back end upon successful Object creation in the Database,
    //    therefore - we are excluding it from being serialized before the transmission of the POST Request
    @Expose (serialize = false, deserialize = true)
    private int id;
    @Expose
    private String name;
    @Expose
    private String email;
    @Expose
    private String gender;
    @Expose
    private String status;

    // 2. Creating a parameterized "UsersPOJO" Constructor, to instantiate the instance variables
    public UsersPOJO (String name, String email, String gender, String status){
        this.name = name;
        this.email = email;
        this.gender = gender;
        this.status = status;
    }
}
